# Generated by Django 4.1.4 on 2022-12-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Маршрут перевозки')),
                ('price', models.CharField(max_length=20, verbose_name='Стоимость перевозки')),
            ],
        ),
    ]
