# Generated by Django 4.1.4 on 2022-12-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loads',
            options={'verbose_name': 'Загрузку', 'verbose_name_plural': 'Загрузки'},
        ),
    ]
