# Generated by Django 4.1.4 on 2022-12-25 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logapps', '0002_alter_loads_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loads',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
